[package]
name = "frl-proxy"
version = "0.9.0"
authors = ["Andrew Dorton <adorton@adobe.com>", "Daniel Brotsky <dbrotsky@adobe.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
hyper-tls = "0.4"
tokio = { version = "0.2", features = ["full"] }
tokio-rustls = "0.14.0"
config = "0.10"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
structopt = "0.3"
eyre = "0.6"
rustls = "0.18"
futures = "0.3"
futures-util = "^0.3.1"
log = "0.4"
fern = "0.6"
chrono = "0.4"
ctrlc = "3.1"
openssl-probe = "0.1.2"
sqlx = { version = "0.4.2", default-features = false, features = [ "runtime-tokio-rustls", "sqlite" ] }
url = "2.1.1"
sys-info = "0.7.0"
