[package]
name = "frl-proxy"
version = "0.1.0"
authors = ["Andrew Dorton <adorton@adobe.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
config = "0.10"
serde = { version = "^1.0.8", features = ["derive"] }
structopt = "0.3"
