# allow unstable features is only allowed in nightly builds
#unstable_features = true

# set the options that control other options
max_width = 90
#width_heuristics = "Max"

# alphabetic list of non-default options
# (unstable ones are commented out)
#combine_control_expr = false
#empty_item_single_line = false
fn_args_layout = "Compressed"
#format_code_in_doc_comments = true
#force_multiline_blocks = true
#format_strings = true
#match_block_trailing_comma = true
#merge_imports = true
#normalize_comments = true
#overflow_delimited_expr = true
#trailing_comma = "Vertical"
use_field_init_shorthand = true
#wrap_comments = true
